baudrate: 230400
cycle_duration: 2000
axis:
  flexion:
    channel: 1
    cpr: 100
    gear_ratio: 50
    speed: 360
    accel: 360
    decel: 360
  abduction:
    channel: 2
    cpr: 100
    gear_ratio: 50
    speed: 100
    accel: 50
    decel: 50
  rotation:
    channel: 3
    cpr: 100
    gear_ratio: 50
    speed: 100
    accel: 50
    decel: 50
  load:
    channel: 4
    cpr: 100
    gear_ratio: 50
    speed: 100
    accel: 50
    decel: 50
