baudrate: 230400
cycle_duration: 2200
ads_gain: 1
ads_range: 1
axis:
  '0':
    name: Flexion
    cpr: 100
    gear_ratio: 50
    speed: 360
    accel: 360
    decel: 360
  '1':
    name: Abduction
    cpr: 100
    gear_ratio: 50
    speed: 100
    accel: 50
    decel: 50
  '2':
    name: Rotation
    cpr: 100
    gear_ratio: 50
    speed: 100
    accel: 50
    decel: 50
  '3':
    name: Load
    cpr: 100
    gear_ratio: 50
    speed: 100
    accel: 50
    decel: 50
loadcell:
  offset: 0
  scale: 1
  units: lbs
  decimals: 2
