baudrate: 230400
cycle_duration: 1000
ads:
  gain: 1
  A0:
    max: 26385
    units: '%'
  A1:
    max: 26385
    units: '%'
  A2:
    max: 26385
    units: '%'
  A3:
    max: 26385
    units: 'V'
    max_voltage: 125
axis:
  '0':
    name: Flexion
    cpr: 100
    gear_ratio: 50
    speed: 360
    accel: 360
    decel: 360
    backlash: 300
  '1':
    name: Abduction
    cpr: 100
    gear_ratio: 50
    speed: 100
    accel: 50
    decel: 50
    backlash: 0
  '2':
    name: Rotation
    cpr: 100
    gear_ratio: 50
    speed: 100
    accel: 50
    decel: 50
    backlash: 0
  '3':
    name: Load
    cpr: 100
    gear_ratio: 50
    speed: 100
    accel: 50
    decel: 50
    backlash: 0
    conversion: 2.44
loadcell:
  offset: 0
  scale: 1
  units: KN
  decimals: 2
